# 01 Setup and Dataset Loading

In [1]:
import pandas as pd

In [2]:
file = "All_Pokemon.csv"

In [4]:
df_pokemons = pd.read_csv(file)

# 02 Initial Inspection

In [6]:
df_pokemons.shape

(1032, 44)

In [7]:
df_pokemons.head()

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,...,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,...,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6

In [8]:
df_pokemons.head(7)

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,...,1.00,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,...,0.50,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6
5,5,Charmeleon,Fire,NaN,"['Blaze', 'Solar Power']",58,64,58,80,65,...,0.50,2.0,1.0,1.0,1.0,0.5,0.5,1.1,19.0,15.7
6,6,Charizard,Fire,Flying,"['Blaze', 'Solar Power']",78,84,78,109,85,...,0.25,4.0,1.0,1.0,1.0,0.5,0.5,1.7,90.5,31.3

In [9]:
df_pokemons.tail(4)

,Number,Name,Type 1,Type 2,Abilities,HP,Att,Def,Spa,Spd,...,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
1028,897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65,60,145,80,...,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,44.5,11.1
1029,898,Calyrex,Psychic,Grass,['Unnerve'],100,80,80,80,80,...,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.1,7.7,6.4
1030,898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,...,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5
1031,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,...,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3

In [10]:
df_pokemons.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1032 entries, 0 to 1031
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Number                   1032 non-null   int64
 1   Name                     1032 non-null   object
 2   Type 1                   1032 non-null   object
 3   Type 2                   548 non-null    object
 4   Abilities                1032 non-null   object
 5   HP                       1032 non-null   int64
 6   Att                      1032 non-null   int64
 7   Def                      1032 non-null   int64
 8   Spa                      1032 non-null   int64
 9   Spd                      1032 non-null   int64
 10  Spe                      1032 non-null   int64
 11  BST                      1032 non-null   int64
 12  Mean                     1032 non-null   float64
 13  Standard Deviation       1032 non-null   float64
 14  Generation               1032 non-null   float64
 15  Experience type          1032 non-null   object
 16  Experience to level 100  1032 non-null   int64
 17  Final Evolution          1032 non-null   float64
 18  Catch Rate               1032 non-null   int64
 19  Legendary                1032 non-null   float64
 20  Mega Evolution           1032 non-null   float64
 21  Alolan Form              1032 non-null   float64
 22  Galarian Form            1032 non-null   float64
 23  Against Normal           1032 non-null   float64
 24  Against Fire             1032 non-null   float64
 25  Against Water            1032 non-null   float64
 26  Against Electric         1032 non-null   float64
 27  Against Grass            1032 non-null   float64
 28  Against Ice              1032 non-null   float64
 29  Against Fighting         1032 non-null   float64
 30  Against Poison           1032 non-null   float64
 31  Against Ground           1032 non-null   float64
 32  Against Flying           1032 non-null   float64
 33  Against Psychic          1032 non-null   float64
 34  Against Bug              1032 non-null   float64
 35  Against Rock             1032 non-null   float64
 36  Against Ghost            1032 non-null   float64
 37  Against Dragon           1032 non-null   float64
 38  Against Dark             1032 non-null   float64
 39  Against Steel            1032 non-null   float64
 40  Against Fairy            1032 non-null   float64
 41  Height                   1032 non-null   float64
 42  Weight                   1032 non-null   float64
 43  BMI                      1032 non-null   float64
dtypes: float64(29), int64(10), object(5)
memory usage: 354.9+ KB

In [20]:
df_pokemons.columns

Index(['Number',
       'Name',
       'Type 1',
       'Type 2',
       'Abilities',
       'HP',
       'Att',
       'Def',
       'Spa',
       'Spd',
       'Spe',
       'BST',
       'Mean',
       'Standard Deviation',
       'Generation',
       'Experience type',
       'Experience to level 100',
       'Final Evolution',
       'Catch Rate',
       'Legendary',
       'Mega Evolution',
       'Alolan Form',
       'Galarian Form',
       'Against Normal',
       'Against Fire',
       'Against Water',
       'Against Electric',
       'Against Grass',
       'Against Ice',
       'Against Fighting',
       'Against Poison',
       'Against Ground',
       'Against Flying',
       'Against Psychic',
       'Against Bug',
       'Against Rock',
       'Against Ghost',
       'Against Dragon',
       'Against Dark',
       'Against Steel',
       'Against Fairy',
       'Height',
       'Weight',
       'BMI'],
      dtype='object')

In [22]:
df_pokemons.dtypes

Number                       int64
Name                        object
Type 1                      object
Type 2                      object
Abilities                   object
HP                           int64
Att                          int64
Def                          int64
Spa                          int64
Spd                          int64
Spe                          int64
BST                          int64
Mean                       float64
Standard Deviation         float64
Generation                 float64
Experience type             object
Experience to level 100      int64
Final Evolution            float64
Catch Rate                   int64
Legendary                  float64
Mega Evolution             float64
Alolan Form                float64
Galarian Form              float64
Against Normal             float64
Against Fire               float64
Against Water              float64
Against Electric           float64
Against Grass              float64
Against Ice                float64
Against Fighting           float64
Against Poison             float64
Against Ground             float64
Against Flying             float64
Against Psychic            float64
Against Bug                float64
Against Rock               float64
Against Ghost              float64
Against Dragon             float64
Against Dark               float64
Against Steel              float64
Against Fairy              float64
Height                     float64
Weight                     float64
BMI                        float64
dtype: object

In [26]:
df_pokemons.describe()

,Number,HP,Att,Def,Spa,Spd,Spe,BST,Mean,Standard Deviation,Generation,Experience to level 100,Final Evolution,Catch Rate,Legendary,Mega Evolution,Alolan Form,Galarian Form,Against Normal,Against Fire,Against Water,Against Electric,Against Grass,Against Ice,Against Fighting,Against Poison,Against Ground,Against Flying,Against Psychic,Against Bug,Against Rock,Against Ghost,Against Dragon,Against Dark,Against Steel,Against Fairy,Height,Weight,BMI
count,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1.032000e+03,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000,1032.000000
mean,439.226744,69.906008,80.526163,74.609496,72.918605,72.139535,68.548450,438.648256,73.108043,20.028104,4.432171,1.061362e+06,0.564922,93.879845,0.121124,0.048450,0.017442,0.019380,0.867490,1.147045,1.061289,1.045785,1.005814,1.210514,1.074612,0.956395,1.128391,1.171996,0.975533,1.002180,1.239826,1.025678,0.974806,1.074855,0.992006,1.094234,1.286822,71.879845,136.735756
std,261.871350,26.189155,32.542374,30.905972,32.773495,27.625876,30.219526,120.675545,20.112591,10.830298,2.263713,1.570876e+05,0.496008,76.316071,0.326430,0.214818,0.130974,0.137923,0.288087,0.703754,0.607551,0.635515,0.748643,0.759727,0.758243,0.544938,0.762139,0.593650,0.500431,0.613111,0.699361,0.577269,0.378040,0.475292,0.511859,0.535159,1.391501,132.872741,3111.666658
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,175.000000,29.166667,0.000000,1.000000,6.000000e+05,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.250000,0.000000,0.250000,0.250000,0.000000,0.000000,0.000000,0.250000,0.000000,0.250000,0.250000,0.000000,0.000000,0.250000,0.250000,0.250000,0.100000,0.100000,0.000000
25%,211.750000,50.000000,55.000000,50.000000,50.000000,50.000000,45.000000,330.000000,55.000000,12.801910,3.000000,1.000000e+06,0.000000,45.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,1.000000,1.000000,1.000000,0.500000,1.000000,1.000000,1.000000,1.000000,0.500000,1.000000,0.600000,9.000000,18.600000
50%,434.500000,67.000000,78.000000,70.000000,65.000000,70.000000,65.000000,459.000000,76.500000,18.484228,5.000000,1.000000e+06,1.000000,60.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,29.750000,28.350000
75%,667.250000,83.000000,100.000000,90.000000,95.000000,90.000000,90.000000,515.000000,85.833333,24.835709,6.000000,1.250000e+06,1.000000,127.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.600000,71.275000,42.200000
max,898.000000,255.000000,190.000000,230.000000,194.000000,230.000000,200.000000,780.000000,130.000000,103.215659,8.000000,1.640000e+06,1.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,2.000000,4.000000,4.000000,4.000000,20.000000,999.900000,99990.000000

In [28]:
import numpy as np

In [32]:
numeric_variables = df_pokemons.select_dtypes(include=np.number).columns.tolist()
numeric_variables

['Number',
 'HP',
 'Att',
 'Def',
 'Spa',
 'Spd',
 'Spe',
 'BST',
 'Mean',
 'Standard Deviation',
 'Generation',
 'Experience to level 100',
 'Final Evolution',
 'Catch Rate',
 'Legendary',
 'Mega Evolution',
 'Alolan Form',
 'Galarian Form',
 'Against Normal',
 'Against Fire',
 'Against Water',
 'Against Electric',
 'Against Grass',
 'Against Ice',
 'Against Fighting',
 'Against Poison',
 'Against Ground',
 'Against Flying',
 'Against Psychic',
 'Against Bug',
 'Against Rock',
 'Against Ghost',
 'Against Dragon',
 'Against Dark',
 'Against Steel',
 'Against Fairy',
 'Height',
 'Weight',
 'BMI']

In [33]:
categorical_variables = df_pokemons.select_dtypes(exclude=np.number).columns.tolist()
categorical_variables

['Name', 'Type 1', 'Type 2', 'Abilities', 'Experience type']

# 03 Data Cleaning

In [73]:
df_clean=df_pokemons
df_clean.head(2)

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.0,8.640988,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,405,67.5,8.902247,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0,Dual Type

In [74]:
df_clean.columns=df_clean.columns.str.strip()
df_clean.head(2)

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.0,8.640988,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,405,67.5,8.902247,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0,Dual Type

In [75]:
df_clean.columns=df_clean.columns.str.lower()
df_clean.head(2)

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.0,8.640988,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,405,67.5,8.902247,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0,Dual Type

In [76]:
df_clean.columns=df_clean.columns.str.replace(' ','_')
df_clean.head(2)

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.0,8.640988,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,405,67.5,8.902247,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0,Dual Type

In [77]:
df_clean["number"].isna().sum()

np.int64(0)

In [78]:
df_clean["name"].isna().sum()

np.int64(0)

In [79]:
df_clean["type_1"].isna().sum()

np.int64(0)

In [80]:
df_clean["type_2"].isna().sum()

np.int64(484)

In [81]:
df_clean["type_2"].isnull().sum()

np.int64(484)

In [82]:
df_clean["type_2"].notna().sum()

np.int64(548)

In [87]:
missing_table = df_clean.isna().sum().to_frame("missing_count")
missing_table

                         missing_count
number                               0
name                                 0
type_1                               0
type_2                             484
abilities                            0
hp                                   0
att                                  0
def                                  0
spa                                  0
spd                                  0
spe                                  0
bst                                  0
mean                                 0
standard_deviation                   0
generation                           0
experience_type                      0
experience_to_level_100              0
final_evolution                      0
catch_rate                           0
legendary_status                     0
mega_evolution                       0
alolan_form                          0
galarian_form                        0
against_normal                       0
against_fire                         0
against_water                        0
against_electric                     0
against_grass                        0
against_ice                          0
against_fighting                     0
against_poison                       0
against_ground                       0
against_flying                       0
against_psychic                      0
against_bug                          0
against_rock                         0
against_ghost                        0
against_dragon                       0
against_dark                         0
against_steel                        0
against_fairy                        0
height                               0
weight                               0
bmi                                  0
number_of_types                      0

In [83]:
df_clean["number_of_types"] = np.where(
    df_clean["type_2"].isna(),
    "Single Type",
    "Dual Type"
)
df_clean

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.000000,8.640988,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,405,67.500000,8.902247,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0,Dual Type
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,525,87.500000,8.902247,1.0,Medium Slow,1059860,1.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0,Dual Type
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,625,104.166667,18.747592,6.0,Medium Slow,1059860,1.0,45,0.0,1.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0,Dual Type
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,65,309,51.500000,8.995369,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,0.5,2.0,1.0,0.50,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6,Single Type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,896,Glastrier,Ice,NaN,['Chilling Neigh'],100,145,130,65,110,30,580,96.666667,38.908725,8.0,Slow,1250000,1.0,3,1.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,1.00,0.5,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.2,800.0,165.3,Single Type
1028,897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65,60,145,80,130,580,96.666667,31.841622,8.0,Slow,1250000,1.0,3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,44.5,11.1,Single Type
1029,898,Calyrex,Psychic,Grass,['Unnerve'],100,80,80,80,80,80,500,83.333333,7.453560,8.0,Slow,1250000,1.0,3,1.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.50,2.0,0.5,2.0,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.1,7.7,6.4,Dual Type
1030,898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,50,680,113.333333,39.334746,8.0,Slow,1250000,1.0,3,1.0,0.0,0.0,0.0,1.0,2.0,1.0,1.0,1.00,0.5,1.0,1.0,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5,Dual Type
1031,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,150,680,113.333333,32.360813,8.0,Slow,1250000,1.0,3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3,Dual Type

In [84]:
df_clean = df_clean.rename(columns={
    "legendary": "legendary_status"
})
df_clean.head(1)

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary_status,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.0,8.640988,1.0,Medium Slow,1059860,0.0,45,0.0,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type

In [85]:
df_clean["legendary_status"] = np.where(
    df_clean["legendary_status"]==0,
    "Non Legendary",
    "Legendary"
)
df_clean

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary_status,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.000000,8.640988,1.0,Medium Slow,1059860,0.0,45,Non Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,405,67.500000,8.902247,1.0,Medium Slow,1059860,0.0,45,Non Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0,Dual Type
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,525,87.500000,8.902247,1.0,Medium Slow,1059860,1.0,45,Non Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0,Dual Type
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,625,104.166667,18.747592,6.0,Medium Slow,1059860,1.0,45,Non Legendary,1.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0,Dual Type
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,65,309,51.500000,8.995369,1.0,Medium Slow,1059860,0.0,45,Non Legendary,0.0,0.0,0.0,1.0,0.5,2.0,1.0,0.50,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6,Single Type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,896,Glastrier,Ice,NaN,['Chilling Neigh'],100,145,130,65,110,30,580,96.666667,38.908725,8.0,Slow,1250000,1.0,3,Legendary,0.0,0.0,0.0,1.0,2.0,1.0,1.0,1.00,0.5,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.2,800.0,165.3,Single Type
1028,897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65,60,145,80,130,580,96.666667,31.841622,8.0,Slow,1250000,1.0,3,Legendary,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,44.5,11.1,Single Type
1029,898,Calyrex,Psychic,Grass,['Unnerve'],100,80,80,80,80,80,500,83.333333,7.453560,8.0,Slow,1250000,1.0,3,Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.50,2.0,0.5,2.0,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.1,7.7,6.4,Dual Type
1030,898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,50,680,113.333333,39.334746,8.0,Slow,1250000,1.0,3,Legendary,0.0,0.0,0.0,1.0,2.0,1.0,1.0,1.00,0.5,1.0,1.0,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5,Dual Type
1031,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,150,680,113.333333,32.360813,8.0,Slow,1250000,1.0,3,Legendary,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3,Dual Type

In [86]:
df_clean["final_evolution"] = np.where(
    df_clean["final_evolution"]==0,
    "Non ultimate",
    "Ultimate"
)
df_clean

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary_status,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.000000,8.640988,1.0,Medium Slow,1059860,Non ultimate,45,Non Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type
1,2,Ivysaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",60,62,63,80,80,60,405,67.500000,8.902247,1.0,Medium Slow,1059860,Non ultimate,45,Non Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,1.0,13.0,13.0,Dual Type
2,3,Venusaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",80,82,83,100,100,80,525,87.500000,8.902247,1.0,Medium Slow,1059860,Ultimate,45,Non Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.0,100.0,25.0,Dual Type
3,3,Mega Venusaur,Grass,Poison,['Thick Fat'],80,100,123,122,120,80,625,104.166667,18.747592,6.0,Medium Slow,1059860,Ultimate,45,Non Legendary,1.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,2.4,155.5,27.0,Dual Type
4,4,Charmander,Fire,NaN,"['Blaze', 'Solar Power']",39,52,43,60,50,65,309,51.500000,8.995369,1.0,Medium Slow,1059860,Non ultimate,45,Non Legendary,0.0,0.0,0.0,1.0,0.5,2.0,1.0,0.50,0.5,1.0,1.0,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5,0.6,8.5,23.6,Single Type
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,896,Glastrier,Ice,NaN,['Chilling Neigh'],100,145,130,65,110,30,580,96.666667,38.908725,8.0,Slow,1250000,Ultimate,3,Legendary,0.0,0.0,0.0,1.0,2.0,1.0,1.0,1.00,0.5,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.2,800.0,165.3,Single Type
1028,897,Spectrier,Ghost,NaN,['Grim Neigh'],100,65,60,145,80,130,580,96.666667,31.841622,8.0,Slow,1250000,Ultimate,3,Legendary,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0,2.0,44.5,11.1,Single Type
1029,898,Calyrex,Psychic,Grass,['Unnerve'],100,80,80,80,80,80,500,83.333333,7.453560,8.0,Slow,1250000,Ultimate,3,Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.50,2.0,0.5,2.0,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0,1.1,7.7,6.4,Dual Type
1030,898,Calyrex Ice Rider,Psychic,Ice,['As One'],100,165,150,85,130,50,680,113.333333,39.334746,8.0,Slow,1250000,Ultimate,3,Legendary,0.0,0.0,0.0,1.0,2.0,1.0,1.0,1.00,0.5,1.0,1.0,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.4,809.1,140.5,Dual Type
1031,898,Calyrex Shadow Rider,Psychic,Ghost,['As One'],100,85,80,165,100,150,680,113.333333,32.360813,8.0,Slow,1250000,Ultimate,3,Legendary,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.00,1.0,0.0,0.5,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0,2.4,53.6,9.3,Dual Type

In [88]:
duplicate_rows = df_clean.duplicated().sum()
duplicate_rows

np.int64(0)

In [90]:
unique_values = df_clean.nunique(dropna=False)
unique_values

number                      898
name                       1032
type_1                       18
type_2                       19
abilities                   602
hp                          103
att                         123
def                         113
spa                         119
spd                         106
spe                         127
bst                         215
mean                        215
standard_deviation          725
generation                    8
experience_type               6
experience_to_level_100       6
final_evolution               2
catch_rate                   34
legendary_status              2
mega_evolution                2
alolan_form                   2
galarian_form                 2
against_normal                4
against_fire                  5
against_water                 5
against_electric              6
against_grass                 5
against_ice                   5
against_fighting              6
against_poison                6
against_ground                6
against_flying                5
against_psychic               6
against_bug                   5
against_rock                  5
against_ghost                 5
against_dragon                4
against_dark                  5
against_steel                 5
against_fairy                 5
height                       60
weight                      473
bmi                         501
number_of_types               2
dtype: int64

# 04 Descriptive Statistics

In [92]:
numerical_variables = df_clean.select_dtypes(include=np.number).columns.tolist()
numerical_variables

['number',
 'hp',
 'att',
 'def',
 'spa',
 'spd',
 'spe',
 'bst',
 'mean',
 'standard_deviation',
 'generation',
 'experience_to_level_100',
 'catch_rate',
 'mega_evolution',
 'alolan_form',
 'galarian_form',
 'against_normal',
 'against_fire',
 'against_water',
 'against_electric',
 'against_grass',
 'against_ice',
 'against_fighting',
 'against_poison',
 'against_ground',
 'against_flying',
 'against_psychic',
 'against_bug',
 'against_rock',
 'against_ghost',
 'against_dragon',
 'against_dark',
 'against_steel',
 'against_fairy',
 'height',
 'weight',
 'bmi']

In [94]:
df_clean.head(1)

,number,name,type_1,type_2,abilities,hp,att,def,spa,spd,spe,bst,mean,standard_deviation,generation,experience_type,experience_to_level_100,final_evolution,catch_rate,legendary_status,mega_evolution,alolan_form,galarian_form,against_normal,against_fire,against_water,against_electric,against_grass,against_ice,against_fighting,against_poison,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy,height,weight,bmi,number_of_types
0,1,Bulbasaur,Grass,Poison,"['Chlorophyll', 'Overgrow']",45,49,49,65,65,45,318,53.0,8.640988,1.0,Medium Slow,1059860,Non ultimate,45,Non Legendary,0.0,0.0,0.0,1.0,2.0,0.5,0.5,0.25,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.7,6.9,14.1,Dual Type

In [95]:
cuantitative_variables = [
 'hp',
 'att',
 'def',
 'spa',
 'spd',
 'spe',
 'bst',
 'mean',

 'standard_deviation',
 'experience_to_level_100',
 'catch_rate',

 'height',
 'weight',
 'bmi']

In [101]:
descriptive_rows = []

for column in cuantitative_variables:
    s = df_clean[column]
    
    
    descriptive_rows.append({
        "variable": column,
        "count": s.count(),
        "mean": round(s.mean(), 2),
        "median": round(s.median(), 2),
        "mode": round(mode_value, 2) if pd.notna(mode_value) else np.nan,
        "min": round(s.min(), 2),
        "max": round(s.max(), 2),
        "range": round(s.max() - s.min(), 2),
        "variance": round(s.var(ddof=1), 2),
        "std_dev": round(s.std(ddof=1), 2),
        "coefficient_of_variation": round(s.std(ddof=1) / s.mean(), 2),
        "Q1": round(s.quantile(0.25), 2),
        "Q2": round(s.quantile(0.50), 2),
        "Q3": round(s.quantile(0.75), 2),
        "IQR": round(s.quantile(0.75) - s.quantile(0.25), 2),
        "P5": round(s.quantile(0.05), 2),
        "P10": round(s.quantile(0.10), 2),
        "P25": round(s.quantile(0.25), 2),
        "P50": round(s.quantile(0.50), 2),
        "P75": round(s.quantile(0.75), 2),
        "P90": round(s.quantile(0.90), 2),
        "P95": round(s.quantile(0.95), 2),
        "skewness": round(s.skew(), 2),
        "kurtosis": round(s.kurt(), 2)
    })

descriptive_statistics = pd.DataFrame(descriptive_rows).set_index("variable")
descriptive_statistics

,count,mean,median,mode,min,max,range,variance,std_dev,coefficient_of_variation,Q1,Q2,Q3,IQR,P5,P10,P25,P50,P75,P90,P95,skewness,kurtosis
variable,,,,,,,,,,,,,,,,,,,,,,,
hp,1032,69.91,67.00,25.0,1.00,255.00,254.00,6.858700e+02,26.19,0.37,50.0,67.00,83.00,33.00,38.00,40.00,50.0,67.00,83.00,100.00,110.00,1.62,7.14
att,1032,80.53,78.00,25.0,5.00,190.00,185.00,1.059010e+03,32.54,0.40,55.0,78.00,100.00,45.00,30.00,40.00,55.0,78.00,100.00,125.00,137.90,0.48,0.01
def,1032,74.61,70.00,25.0,5.00,230.00,225.00,9.551800e+02,30.91,0.41,50.0,70.00,90.00,40.00,35.00,40.00,50.0,70.00,90.00,115.00,130.00,1.06,2.32
spa,1032,72.92,65.00,25.0,10.00,194.00,184.00,1.074100e+03,32.77,0.45,50.0,65.00,95.00,45.00,30.00,35.00,50.0,65.00,95.00,120.00,135.00,0.73,0.23
spd,1032,72.14,70.00,25.0,20.00,230.00,210.00,7.631900e+02,27.63,0.38,50.0,70.00,90.00,40.00,33.55,40.00,50.0,70.00,90.00,108.90,120.00,0.75,1.17
spe,1032,68.55,65.00,25.0,5.00,200.00,195.00,9.132200e+02,30.22,0.44,45.0,65.00,90.00,45.00,25.00,30.00,45.0,65.00,90.00,109.00,120.00,0.45,-0.04
bst,1032,438.65,459.00,25.0,175.00,780.00,605.00,1.456259e+04,120.68,0.28,330.0,459.00,515.00,185.00,250.00,281.30,330.0,459.00,515.00,600.00,630.00,0.08,-0.53
mean,1032,73.11,76.50,25.0,29.17,130.00,100.83,4.045200e+02,20.11,0.28,55.0,76.50,85.83,30.83,41.67,46.88,55.0,76.50,85.83,100.00,105.00,0.08,-0.53
standard_deviation,1032,20.03,18.48,25.0,0.00,103.22,103.22,1.173000e+02,10.83,0.54,12.8,18.48,24.84,12.03,6.87,8.90,12.8,18.48,24.84,32.98,38.97,1.71,6.80
experience_to_level_100,1032,1061362.11,1000000.00,25.0,600000.00,1640000.00,1040000.00,2.467652e+10,157087.61,0.15,1000000.0,1000000.00,1250000.00,250000.00,800000.00,1000000.00,1000000.0,1000000.00,1250000.00,1250000.00,1250000.00,0.14,2.42
catch_rate,1032,93.88,60.00,25.0,3.00,255.00,252.00,5.824140e+03,76.32,0.81,45.0,60.00,127.00,82.00,3.00,25.00,45.0,60.00,127.00,225.00,255.00,0.94,-0.40
height,1032,1.29,1.00,25.0,0.10,20.00,19.90,1.940000e+00,1.39,1.08,0.6,1.00,1.60,1.00,0.30,0.31,0.6,1.00,1.60,2.10,3.00,5.65,50.42
weight,1032,71.88,29.75,25.0,0.10,999.90,999.80,1.765517e+04,132.87,1.85,9.0,29.75,71.28,62.28,1.20,3.20,9.0,29.75,71.28,177.70,307.25,4.20,21.05
bmi,1032,136.74,28.35,25.0,0.00,99990.00,99990.00,9.682469e+06,3111.67,22.76,18.6,28.35,42.20,23.60,5.60,9.46,18.6,28.35,42.20,79.24,115.22,32.11,1031.53